name: meal_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  google_sign_in: ^7.1.1
  supabase_flutter: ^2.9.1
  equatable: ^2.0.7
  app_links: ^6.4.0
  flutter_native_splash: ^2.4.6
  google_nav_bar: ^5.0.7
  google_generative_ai: ^0.4.7
  http: ^1.5.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  flutter_dotenv: ^6.0.0
 


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboardingimages/well-done-steak-homemade-potatoes 1@2x.png
    - assets/images/onboardingimages/Chef Hat.png
    - assets/images/onboardingimages/Ellipse 39.png
    - assets/images/onboardingimages/Ellipse 7 (2).png
    - assets/images/onboardingimages/pizza-pizza-filled-with-tomatoes-salami-olives 1.png
    - assets/images/onboardingimages/view-tasty-shawarma-dish 2.png
    - assets/images/onboardingimages/heart (1).png
    - assets/images/
    - api_key.env
    

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
